AAFC-BICoE/dina-local-deployment

- README.md
- keycloak-dina-starter-realm.json
Upgrades the dina-admin user to have a real group/role permission of `aafc/dina-admin`
> 22980 update keycloack json for dina admin

- docker-compose.base.yml
> Update to dina-db-init-container 0.2

- keycloak-dina-starter-realm.json
add dao-cm and ccfc-cm users. Tested and working.
> add_additional_users

- docker-compose.local.yml
add setting change to disable auto create
> 24714_diasable_es_auto_index_creation

- docker-compose.local.yml
- elastic-configurator-settings/collection-index/dina_material_sample_index_settings.json
update dina_material_sample_index_settings.json for collecting event include
> 24746_coll_event_in_mat_sample_index

- docker-compose.base.yml
- docs/PostgresqlMajorUpdate.md
dina-db: image: "postgis/postgis:12-3.1-alpine"
> 25368_dina_db_postgis_12

- README.md
- keycloak-dina-starter-realm.json
https://redmine.biodiversity.agr.gc.ca/issues/25820
> Support #25820 - Add keycloak read only role

- docker-compose.local.yml
Traefik should use the dina network to contact apis that are on 2 networks
> Set api network in Traefik

- docker-compose.base.yml
> 25679 Try Keycloak 15.1

- README.md
- config/prometheus.yml
- docker-compose.local.yml
Added prometheus to local compose file (with a specific profile) + config file to connect to collection-api
> 27048 Add prometheus to local-deployment

- docker-compose.base.yml
- docker-compose.local.yml
https://redmine.biodiversity.agr.gc.ca/issues/27143
> Added healthcheck to docker files

- docker-compose.local.yml
- elastic-configurator-settings/collection-index/dina_material_sample_index_settings.json
Updated search images and added mapping for preparation-type
> 27517 Update search-api to 0.16

- docker-compose.local.yml
- elastic-configurator-settings/collection-index/dina_material_sample_index_settings.json
- elasticsearch/Dockerfile
Add a field to materialSampleName that can sort on the numeric part
> Build a local image of elasticsearch with the icu plugin

- elastic-configurator-settings/collection-index/dina_material_sample_index_settings.json
> 28394 Add assemblage relationship to mat-sample mapping

- elastic-configurator-settings/collection-index/dina_material_sample_index_settings.json
Add projects to material-sample mapping
> 28630 Add more search-ws mapping options

- elastic-configurator-settings/agent-index/dina_agent_index_settings.json
- elastic-configurator-settings/collection-index/dina_material_sample_index_settings.json
- elastic-configurator-settings/dina_loan_transaction_index_settings.json
- elastic-configurator-settings/object-store-index/object_store_index_settings.json
- elastic-configurator-settings/storage-index/dina_storage_index_settings.json
Disable date_detection for all index
> 29427 Improve index mapping

- .env
- docker-compose.local.yml
- Added INSTANCE_MODE flag to .env and local.yml file to determine the build mode
> 29682 Add visual indicator of the environment

- elastic-configurator-settings/dina_loan_transaction_index_settings.json
- Added nested materialSamples mapping to loan transaction index settings
> 30378 Loan Transaction index add nested explicit mapping

- docker-compose.local.yml
- Updated to version RELEASE.2022-10-05T14-58-27Z
> Support #29962 - Upgrade MinIO

- docker-compose.local.yml
- elasticsearch/Dockerfile
> 30785 Upgrade ElasticSearch image

- docker-compose.local.yml
- Changed the volume to work like Minio
- Updated the Docker image of RabbitMQ
> 31242 Change rabbit-mq volume settings

- azure-pipelines.yml
- jmeter/collection_api_module_testplan.jmx
* Random variable creation and referencing has been updated which has resolved the stack trace issue locally
> Support 31518 JMeter Azure Stack Trace

- docker-compose.local.yml
- Add elastic search host and port to dina-export-api environment
> 31604 Add export button and view

- docker-compose.base.yml
- keycloak/Dockerfile
Update base image of the custom build + update tag in Compose file
> 31722 Update Keycloak to 20

- .env
- docker-compose.local.yml
- Added supported languages iso to .env file and docker-compose.local.yml
> 32536 Allow to configure languages

- elastic-configurator-settings/collection-index/dina_material_sample_index_settings.json
Added dynamic_templates for dwcVerbatim*
> 32389 material-sample index not detailed enough

- elastic-configurator-settings/object-store-index/object_store_index_settings.json
Added new mapping configuration
> 33717 Add suffix and keyword_numeric to originalFileName

- helm/Chart.yaml
- helm/README.md
- helm/config/keycloak/keycloak-dina-starter-realm.json
- helm/templates/configMaps/configMaps.yaml
- helm/templates/deployments/keycloak.yaml
- helm/templates/secrets/auto.secrets.yaml
- helm/values.yaml
Updated images and chart version
> Update Helm chart 1.10

- helm/config/keycloak/keycloak-dina-starter-realm.json
- keycloak/keycloak-dina-starter-realm.json
- Removed groups from dina-admin user
- Removed aafc/dina-admin subgroup
> 35670 Change local deployment dina-admin

- helm/templates/_helpers.tpl
- helm/templates/deployments/seqdb-api.yaml
- helm/values.yaml
- created a helper file for reusable functions
- added java_opts for seqdb-api
- updated collection-api to use new helper function
> Support #36124 Add JAVA_OPT to seqdb-api

- helm/templates/deployments/collection-api.yaml
- helm/templates/deployments/seqdb-api.yaml
- helm/values.yaml
* switch from JAVA_OPTS to JDK_JAVA_OPTIONS
* switched to using XX:MaxRAMPercentage instead of hardcoding max RAM
> Support #36332 JAVA_OPTS being ignored

- docker-compose.dev.yml
- docs/developer_environment.adoc
- Updated the dina-ui-dev-server to use node 20 (will use the latest version, not specifically version 20.0.0)
- Updated the developer setup to install this version.
> Support #36371 - Upgrade to NodeJS 20.19.1

- docker-compose.base.yml
- helm/values.yaml
- keycloak/Dockerfile
* updated keycloak image version to 22.0.5
> 34992 Update to Keycloak 22
